name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        uses: gradle/gradle-build-action@v2.1.6
        with:
          arguments: build --stacktrace
